sudo: true

install:
- curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
- ./run "docker version && docker info"
- ./run docker run ubuntu /bin/echo hello world
- wget https://gist.githubusercontent.com/moul/0f53ae391ae7d7116e24/raw/23307093546b6ae2f94208c188f5ce4fca2be996/docker-compose.yml
- ./run docker-compose build test
- ./run "docker-compose up test && echo Yeah"
